//LOGITECH F710 defines and struct format from
//https://atariwiki.org/wiki/Wiki.jsp?page=How%2Bto%2Bwrite%2Ba%2BUSB%2BDriver
const char LOGITECH_DPAD[] = {0x1, 0x9, 0x8, 0xA, 0x2, 0x6, 0x4, 0x5, 0x0};		/*REVISAR UPRIGHT...*/
#define LOGITECH_GAMEPAD_START 0x20
#define LOGITECH_GAMEPAD_BACK 0x10
#define LOGITECH_GAMEPAD_LEFT_THUMB 0x40
#define LOGITECH_GAMEPAD_RIGHT_THUMB 0x80
#define LOGITECH_GAMEPAD_LEFT_SHOULDER 0x01
#define LOGITECH_GAMEPAD_RIGHT_SHOULDER 0x02
#define LOGITECH_GAMEPAD_LEFT_TRIGGER 0x04
#define LOGITECH_GAMEPAD_RIGHT_TRIGGER 0x08
//#define LOGITECH_GAMEPAD_GUIDE 0x0400  //NO GUIDE
#define LOGITECH_GAMEPAD_A 0x20
#define LOGITECH_GAMEPAD_B 0x40
#define LOGITECH_GAMEPAD_X 0x10
#define LOGITECH_GAMEPAD_Y 0x80

//PS3 CONTROLLER defines and struct format from
#define PS3_GAMEPAD_DPAD_UP 0x10
#define PS3_GAMEPAD_DPAD_RIGHT 0x20
#define PS3_GAMEPAD_DPAD_DOWN 0x40
#define PS3_GAMEPAD_DPAD_LEFT 0x80
#define PS3_GAMEPAD_CROSS 0x40
#define PS3_GAMEPAD_CIRCLE 0x20
#define PS3_GAMEPAD_SQUARE 0x80
#define PS3_GAMEPAD_TRIANGLE 0x10
#define PS3_GAMEPAD_L2 0x1
#define PS3_GAMEPAD_L1 0x2
#define PS3_GAMEPAD_R1 0x4
#define PS3_GAMEPAD_R2 0x8
#define PS3_GAMEPAD_START 0x8
#define PS3_GAMEPAD_SELECT 0x1
#define PS3_GAMEPAD_L3 0x2
#define PS3_GAMEPAD_R3 0x4
/*TRIGGER TIENEN SU PROPIO BYTE TAMBIEN*/

//8BITDO CONTROLLER defines and struct format from
#define EIGHT_BITDO_GAMEPAD_START 0x08
#define EIGHT_BITDO_GAMEPAD_BACK 0x04
#define EIGHT_BITDO_GAMEPAD_LEFT_THUMB 0x20
#define EIGHT_BITDO_GAMEPAD_RIGHT_THUMB 0x40
#define EIGHT_BITDO_GAMEPAD_LEFT_SHOULDER 0x40
#define EIGHT_BITDO_GAMEPAD_RIGHT_SHOULDER 0x80
#define EIGHT_BITDO_GAMEPAD_LEFT_TRIGGER 0x01
#define EIGHT_BITDO_GAMEPAD_RIGHT_TRIGGER 0x02
//#define EIGHT_BITDO_GAMEPAD_GUIDE 0x0400  //NO GUIDE
#define EIGHT_BITDO_GAMEPAD_A 0x01
#define EIGHT_BITDO_GAMEPAD_B 0x02
#define EIGHT_BITDO_GAMEPAD_X 0x08
#define EIGHT_BITDO_GAMEPAD_Y 0x10