name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [pico, pico_w, pico2, pico2_w, waveshare_rp2350_usb_a]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      
      - name: Build
        run: |
          mkdir build
          cd build
          export PICO_SDK_PATH=../pico-sdk
          cmake ../src -DPICO_BOARD=${{ matrix.board }}
          make -j4

      - name: Upload uf2
        uses: actions/upload-artifact@v7
        with:
          name: PicoGamepadConverter-${{ matrix.board }}
          path: build/PicoGamepadConverter.uf2
